### PR TITLE
Add automatic code analysis using chatGPT API

### PR DESCRIPTION
**Pull request by BrieucDandoy**
# Add automatic code analysis using chatGPT API
- Add .gitignore
- Add requirements.txt
- Change the way lines are counted
- Change the way files are counted
- Add Analysis with ChatGPT API (need API key)
- Add a list of supported programming languages and files extensions

### CODE REVIEW

**Review by hugodemenez — COMMENTED** [review]
Idea: Can we use json strict formatting from OpenAI to GPT response to ensure results ? https://platform.openai.com/docs/guides/text-generation/chat-completions-api

**Comment by BrieucDandoy** [comment]
I think it is already the case in this code sample in ``analysis\ML_analyser.py``. Unless I am missing something ?

``` python
response = self.client.chat.completions.create(
model="gpt-3.5-turbo-0125",
response_format={ "type": "json_object" },
messages=message
)
```

**Comment by hugodemenez** [comment]
Correct ! Don't know why I didn't see it. 👌

**Comment by hugodemenez** [comment]
We can merge then ? I'll add database link and automation with website

**Pull request merged**
